Closes #19: Adding capability for charged particle motion in electric and magnetic fields
idaholab/salamander pull request #20
Opened 2024-03-15 14:31 UTC by gsgall

- VelocityUpdater was refactored to ParticleStepper to be more descriptive
- The updateVelocity method was changed to setupStep since it does more than just update the particle velocity

(Closes #19)

2024-03-15 14:54 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2145068/) on 1ca808c wanted to post the following:

View the site [here](https://fenix-dev.hpc.inl.gov/PRs/20/site)

This comment will be updated on new commits.

2024-03-15 15:41 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2145072/) on 1ca808c wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>042c1a</th>
      <th colspan=4>#20 1ca808</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>91.53%</td>
      <td>91.90%</td>
      <td>+0.38%</td>
      <td>94.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>162</td>
      <td>227</td>
      <td>+65</td>
      <td>94</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>15</td>
      <td>20</td>
      <td>+5</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://fenix-dev.hpc.inl.gov/PRs/20/coverage_diff)

[Full coverage report](https://fenix-dev.hpc.inl.gov/PRs/20/coverage)



This comment will be updated on new commits.

2024-03-26 17:12 UTC, simopier requested changes
Thank you for this contribution!

A partial first round of reviews (I did not make it to the tests yet). 
It looks like a lot of comments, but these are generally minor since you submitted a very good base.  

EDIT: by the way @gsgall , Casey taught me something I'm now sharing every chance I get: if you go to the `file changes`, you can submit commits in batches from suggestions. 

Let me know if you have any questions.

2024-03-26 17:12 UTC, simopier commented on doc/content/bib/boris.bib
> +@article{qin2013boris,
Could you rename this bib file? `boris.bib` is very specific, and we probably want something more general that would contain all the references. Maybe `references.bib`?

2024-03-26 17:12 UTC, simopier commented on src/userobjects/BorisStepper.C
> +      "Electromagnetic particle stepper method implementing the Boris Algorithm");
```suggestion
      "Electromagnetic particle stepper method implementing the Boris Algorithm.");
```

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/BorisStepper.md
> +\end{equation}
The documentation should follow the same guidance provided in the paper: equations need to be part of sentences, notations need to be defined, etc. 

I reproduced the content of the paper with some additional links to other documentation page and test input files. 
By the way, do you have a test for the constant electric field? You could add a link to it like I did for the other two tests. 


```suggestion
In magnetized (or electromagnetic) PIC simulations, the de facto standard particle stepping algorithm is commonly known as the Boris algorithm [!cite](boris1970relativistic,Birdsall_Langdon_1991, qin2013boris). This algorithm is similar to a [Leap Frog method](userobjects/LeapFrogStepper.md) and has second order accuracy in time when solving the equations of motion for a charged particle, given by
\begin{equation} \label{eq:pos}
  \diff{\vec{r}}{t}
  =
  \vec{v}
\end{equation}
and 
\begin{equation} \label{eq:vel}
  \diff{\vec{v}}{t}
  =
  \frac{q}{m}
  \left[
    \vec{E}
    +
    \vec{v}
    \times
    \vec{B}
  \right]
\end{equation}
where $q$ is the particle's charge, $m$ is the particle's mass, and  $\vec{E}$ and $\vec{B}$ are the electric and magnetic fields that the particle is subject to, respectively.

In the Boris algorithm, \cref{eq:pos,eq:vel} are discretized with a central difference scheme and the acceleration due to the electric field and magnetic field are separated. First, half of the impulse due to the electric field is applied to the particle, as  
\begin{equation} \label{eq:e_half1}
  \vec{v}^{\,-}
  =
  \vec{v}_{n}
  +
  \frac{q}{m}
  \vec{E}_n
  \frac{\Delta t}{2}
\end{equation}
where $\vec{v}^{\,-}$ is an intermediate particle velocity, $\vec{v}_{n}$ is the particle velocity at step $n$, and $\vec{E}_{n}$ is the electric field at step $n$. The velocity of the particle after rotation due to the magnetic field is derived as
\begin{equation} \label{eq:boris_v_plus}
  \vec{v}^{\,+}
  =
  \vec{v}^{\,-}
  +
  \vec{v}^{\,'}
  \times
  \vec{s},
\end{equation}
with 
\begin{equation} \label{eq:boris_v_prime}
  \vec{v}^{\,'}
  =
  \vec{v}^{\,-}
  +
  \vec{v}^{\,-}
  \times
  \vec{l}
\end{equation}
where 
\begin{equation} \label{eq:boris_t}
  \vec{l} =
  \frac{q}{m}
  \vec{B}_n
  \Delta t,
\end{equation}
which accounts for the effect of $\vec{B}_n$, the magnetic field at step $n$. $\vec{s}$ is defined as
\begin{equation} \label{eq:boris_s}
  \vec{s} =
  \frac{2 \vec{l}}{
    1 + \vec{l} \cdot \vec{l}
  }.
\end{equation}
Finally, the rotation due to the presence of the magnetic field is then applied with
\begin{equation} \label{eq:mag_step}
  \frac{
    \vec{v}^{\,+}
    -
    \vec{v}^{\,-}
  }{ \Delta t}
  =
  \frac{q}{m}
  \left(
    \vec{v}^{\,+}
    +
    \vec{v}^{\,-}
  \right)
  \times
  \vec{B}_n,
\end{equation}
and the final impulse due to the electric field is then applied to the particle using 
\begin{equation} \label{eq:e_half2}
  \vec{v}_{n+1}
  =
  \vec{v}^{\,+}
  +
  \frac{q}{m}
  \vec{E}_n
  \frac{\Delta t}{2}.
\end{equation}
The implementation of the Boris algorithm was verified using several single particle motion tests: constant electric field, cyclotron motion ([/cyclotron_motion.i]), and $\vec{E} \times \vec{B}$ drift motion ([/e_cross_b.i]).
```

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/BorisStepper.md
> +!bibtex list bib_files=boris.bib
```suggestion
```

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +On the first step that a particle takes the particle velocity is updated with a 1/2 time step
```suggestion
On the first step that a particle takes the particle velocity is updated with a 1/2 time step as
```

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +\end{equation}
please explain all the notations (see comments provided in `BorisStepper.md`)
```suggestion
\begin{equation}
  \vec{v}_{1/2} = \vec{v}_0 + \frac{q}{m} \vec{F} \frac{dt}{2},
\end{equation}
where ...
```

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +The particle position is then updated with a full time step
```suggestion
The particle position is then updated with a full time step as
```

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +\end{equation}
```suggestion
\begin{equation}
  \vec{r}_{1} = \vec{r}_0 + \vec{v}_{1/2} dt,
\end{equation}
with ....
```

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +\end{equation}
Again, please describe notations.

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +For every other time step, n, after the initial both are updated with a full time step and
```suggestion
For every other time step, $n$, after the initial both are updated with a full time step and
```
Are you missing a word in ` after the initial both` ?

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +\end{equation}
Make sure to incorporate these equations in a sentence and define the notations that have not yet been defined.

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +# LeapFrogStepper
Do you have references for this approach? Please add it to this page. You can also add your submitted paper on this page and the BorisStepper page, we'll just update it once it's published.

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +
Could you please add more context here? Why is this method important? What is it used for?

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/BorisStepper.md
> +!syntax children /UserObjects/BorisStepper
```suggestion
!syntax children /UserObjects/BorisStepper

!bibtex bibliography
```

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/ParticleStepperBase.md
> +`ParticleStepperBase` is the abstract class form which all steppers should be derrived. `ParticleStepperBase` provides the basic method to update a particles direction and maximum distance based on t
```suggestion
`ParticleStepperBase` is the abstract class form which all steppers should be derived. `ParticleStepperBase` provides the basic method to update a particles direction and maximum distance based on the velocity stored in ray data, the current time step and dimension of the mesh. Addtionally, several other useful methods are provided. In the provided method `setMaxDistanceAndDirection` the particles velocity is updated to the newly calculated velocity, the direction is set based on the dimension of the mesh, and the maximum distance is set with the following rule:
```
Could you expand and provide more details about `Addtionally, several other useful methods are provided`?

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/ParticleStepperBase.md
> +\end{equation}
```suggestion
\begin{equation}
  d_\text{max} = \vec{v} \cdot \vec{v} \: dt,
\end{equation}
with ....
```
Please explain the notations.

2024-03-26 17:12 UTC, simopier commented on doc/content/source/userobjects/ParticleStepperBase.md
> +However, only the components of the velocity data corrisponding to the dimension of the mesh will be used in the calculation. If the mesh is 2D then only the first 2 components of velocity will be us
```suggestion
However, only the components of the velocity data corresponding to the dimension of the mesh will be used in the calculation. If the mesh is 2D then only the first 2 components of velocity will be used for this calculation. This calculation is performed with `ParticleStepperBase::setupStep`. This function takes an argument of the ray that needs its velocity updated, the new velocity of the ray and a time step to be used for the maximum distance calculation to allow flexibility for particle pushing methods.

!syntax parameters /UserObjects/ParticleStepperBase

!syntax inputs /UserObjects/ParticleStepperBase

!syntax children /UserObjects/ParticleStepperBase
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/BorisStepper.h
> +// MOOSE Includes
I think this can be removed.
```suggestion
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/LeapFrogStepper.h
> +// MOOSE Includes
```suggestion
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/LeapFrogStepper.h
> +  /// the variable names for each componet of the force vector
```suggestion
  /// the variable names for each component of the force vector
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/PICStudyBase.h
> +  Point _temp_velocity;
`temp` can sometimes be used for temperature, so using the full name could avoid confusion. 
```suggestion
  const Elem * _temporary_elem;
  Point _temporary_point;
  Real _temporary_distance;
  Point _temporary_velocity;
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +// MOOSE Includes
```suggestion
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +   * velocity. The particles velocity data should be updated in this function
```suggestion
   * Method available for override to define the rules by which particles' velocity
   * is updated. The particles' velocity data should be updated in this function.
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +   * Method for a simple dimension dependent update of the rays max distance and
```suggestion
   * Method for a simple dimension-dependent update of the rays max distance and
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +   * @param dt the time step which you are using to set the maximum distance
```suggestion
   * @param dt the time step used to set the maximum distance
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +   * @param ray the ray whose velocity we want to set
```suggestion
   * @param ray the ray whose velocity is being set
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +   * @param v the new velocity that you want the ray to have
```suggestion
   * @param v the new ray velocity
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +   * @param ray the current ray you are updating
Please avoid using `you`, and `we` in the comments. 
```suggestion
   * @param ray the current ray
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +   * @param dt the time step through which you are accelerating the particle
```suggestion
   * @param dt the time step
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +  /// the dimension of the mesh being using used for dimension dependent velocity updates
```suggestion
  /// the dimension of the mesh being using used for dimension-dependent velocity updates
```

2024-03-26 17:12 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +  const Real _dim;
More explicit names help avoid confusion and make code easier to read. 
Disregard if `_dim` is commonly used in ray tracing, but keep this general guidance in mind. 
```suggestion
  const Real _mesh_dimension;
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/BorisStepper.C
> +      "A list of 3 variables which represent the 3 componets of the electric field");
```suggestion
      "A list of 3 variables which represent the 3 components of the electric field");
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/BorisStepper.C
> +      "A list of 3 variables which represent the 3 componets of the electric field");
```suggestion
      "A list of 3 variables which represent the 3 components of the electric field");
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/BorisStepper.C
> +               ": You must provide 3 componets representing the electric field!");
```suggestion
               ": You must provide 3 components representing the electric field!");
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/BorisStepper.C
> +               ": You must provide 3 componets representing the magnetic field!");
```suggestion
               ": You must provide 3 components representing the magnetic field!");
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/BorisStepper.C
> +  // other wise we take a full step
```suggestion
  // otherwise we take a full step
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/BorisStepper.C
> +  // lets sample the fields at the ray location so we can upate the velocity properly
```suggestion
  // let's sample the fields at the ray location so we can update the velocity properly
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/LeapFrogStepper.C
> +      "A list of 3 variables which represent the 3 componets of the force field acting on "
```suggestion
      "A list of 3 variables which represent the 3 components of the force field acting on "
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/LeapFrogStepper.C
> +               ": You must provide 3 componets representing the force field!");
```suggestion
               ": You must provide 3 components representing the force field!");
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/PICStudyBase.C
> +    _temp_distance = ray->distance();
```suggestion
    _temporary_elem = ray->currentElem();
    _temporary_point = ray->currentPoint();
    _temporary_distance = ray->distance();
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/PICStudyBase.C
> +    getVelocity(*ray, _temp_velocity);
```suggestion
    getVelocity(*ray, _temporary_velocity);
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/PICStudyBase.C
> +    setVelocity(*ray, _temp_velocity);
```suggestion
    ray->setStart(_temporary_point, _temporary_elem);
    _stepper.setupStep(*ray,
                       _temporary_velocity,
                       ray->data()[_charge_index] / ray->data()[_mass_index],
                       _temporary_distance);

    setVelocity(*ray, _temporary_velocity);
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/ParticleStepperBase.C
> +                             "And the ability to sample vector fields for use in a paritcle step");
```suggestion
                             "And the ability to sample vector fields for use in a particle step");
```

2024-03-26 17:12 UTC, simopier commented on src/userobjects/ParticleStepperBase.C
> +  ray.setStartingMaxDistance(max_dist);
```suggestion
  const auto max_distance = std::sqrt(velocity * velocity) * dt;

  ray.setStartingMaxDistance(max_distance);
```

2024-03-26 20:59 UTC, simopier commented
I just looked at the test coverage, @gsgall: 
- you'll want to add tests activating the error from `if (******.size() != 3)` check. 
- Also, it looks like the `unused methods` in `ParticleStepperBase` are indeed unused. Do they need to stay there? (@loganharbour)
-  it also look like the following lines are not hit:
``` 
const std::vector<std::shared_ptr<Ray>> &
PICStudyBase::getBankedRays() const
{
  return _banked_rays;
}
```
What are they for?

2024-03-27 03:33 UTC, loganharbour requested changes
All pretty minor here.

2024-03-27 03:33 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  const std::vector<std::shared_ptr<Ray>> & getBankedRays() const;
This isn't used?

2024-03-27 03:33 UTC, loganharbour commented on src/userobjects/PICStudyBase.C
> +    _temp_distance = ray->distance();
Don't bother with using shared state here.

```
const auto elem = ray->currentElem();
const auto point = ray->currentPoint();
const auto distance = ray->distance();
```

The overhead for constructing these is minimal. In most cases, the compiler is smarter than you and will move them outside of the loop and reuse them. This is a micro-optimization that just introduces confusion for little gain

2024-03-27 03:33 UTC, loganharbour commented on include/userobjects/PICStudyBase.h
> +  Point _temp_velocity;
Left a comment in the source; these should be removed

2024-03-27 03:33 UTC, loganharbour commented on include/userobjects/ParticleStepperBase.h
> +  virtual void execute() override {}
```suggestion
  virtual void initialize() override final {}
  virtual void finalize() override final {}
  virtual void execute() override final {}
```

With this, you'll get an error if you try to override in a derived class. Just adds more intent

2024-03-27 03:33 UTC, loganharbour commented on src/userobjects/BorisStepper.C
> +    mooseError("BorisStepper with name ",
paramError

2024-03-27 03:33 UTC, loganharbour commented on src/userobjects/BorisStepper.C
> +    mooseError("BorisStepper with name ",
First, you don't need to add context to mooseErrors within a MooseObject. They already have context. The errors look something like this:

```
*** ERROR **

/path/to/object/in/input.i:5.4
The following error occurred in the object "object_name" of type BorisStepper:

<your error here>
```

Secondly, these should be paramErrors, because they're attributed directly to a parameter:

```
paramError("efield_components, "Must provide three components");
```

2024-03-27 03:33 UTC, loganharbour commented on src/userobjects/LeapFrogStepper.C
> +    mooseError("LeapFrogStepper with name ",
paramError

2024-03-27 03:33 UTC, loganharbour commented on src/userobjects/LeapFrogStepper.C
> +  setMaxDistanceAndDirection(ray, v, _dt);
```suggestion
  const auto dt = distance == 0 ? _dt / 2 : _dt;
  v = linearImpulse(v, F, q_m_ratio, dt);
  setMaxDistanceAndDirection(ray, v, dt);
```

2024-03-27 03:33 UTC, loganharbour commented on src/userobjects/PICStudyBase.C
> +  v(2) = ray.data()[_v_z_index];
Not a requirement, but in the future do this:

```
  v(0) = ray.data(_v_x_index);
  v(1) = ray.data(_v_y_index);
  v(2) = ray.data(_v_z_index);
```

The data(std::size_t index) method has bounds checking in debug

2024-03-27 03:33 UTC, loganharbour commented on src/userobjects/ParticleStepperBase.C
> +  if (v.absolute_fuzzy_equals(Point(0, 0, 0)))
Comment for why?

2024-03-27 03:33 UTC, loganharbour commented on test/tests/userobjects/boris_stepper/cyclotron_motion.i
> +  [Ex_null]
If you're trying to avoid the errors about not having kernels here, you can do

`Problem/kernel_coverage_check=false` 

and can remove these kernels.

2024-03-27 03:34 UTC, loganharbour commented
>  it also look like the following lines are not hit:

Heh @simopier noticed without even looking at the coverage 😬

2024-03-27 03:49 UTC, gsgall commented on include/userobjects/PICStudyBase.h
> +  const std::vector<std::shared_ptr<Ray>> & getBankedRays() const;
That is left over from when was using a custom post processor object for the test cases.I just forgot to remove it when I moved to exodiffs for the tests. I'll go ahead and remove it.

2024-03-27 04:05 UTC, gsgall commented on src/userobjects/PICStudyBase.C
> +  v(2) = ray.data()[_v_z_index];
This change was made in both the `getVelocity` and `setVelocity` methods

2024-03-27 04:09 UTC, gsgall commented on src/userobjects/BorisStepper.C
> +    mooseError("BorisStepper with name ",
This change was made in both the `BorisStepper` and the `LeapfrogStepper` objects

2024-03-27 04:10 UTC, gsgall commented on src/userobjects/PICStudyBase.C
> +    _temp_distance = ray->distance();
Thank you for the explanation! I have made this change.

2024-03-27 04:20 UTC, gsgall commented on test/tests/userobjects/boris_stepper/cyclotron_motion.i
> +  [Ex_null]
Thank you telling me about this!

This change was made in all of the new test cases.

2024-03-27 18:45 UTC, gsgall commented on doc/content/source/userobjects/ParticleStepperBase.md
> +However, only the components of the velocity data corrisponding to the dimension of the mesh will be used in the calculation. If the mesh is 2D then only the first 2 components of velocity will be us
The !syntax commands on this page have been excluded. The particle stepper base is an abstract base class and will never be used directly by end users. These also break the docs when they are added.

2024-03-27 20:15 UTC, gsgall commented on doc/content/bib/boris.bib
> +@article{qin2013boris,
This file has been renamed to references.bib

2024-03-27 20:16 UTC, gsgall commented on doc/content/source/userobjects/LeapFrogStepper.md
> +
More context has been added

2024-03-27 20:31 UTC, gsgall commented on doc/content/source/userobjects/LeapFrogStepper.md
> +# LeapFrogStepper
There is some more detail about this in the Birdsall Langdon book and it has been added as a reference

2024-03-27 20:40 UTC, gsgall commented on doc/content/source/userobjects/ParticleStepperBase.md
> +`ParticleStepperBase` is the abstract class form which all steppers should be derrived. `ParticleStepperBase` provides the basic method to update a particles direction and maximum distance based on t
I have removed this and now it only discusses the other method that is still

2024-03-27 20:42 UTC, gsgall commented
> > it also look like the following lines are not hit:
> 
> Heh @simopier noticed without even looking at the coverage 😬

Sorry about that. I was using that method when I had written a test that output rayData into csv with a custom post processor object. I forgot to remove it when I transitioned the tests to be exodiffs because the post processor test was not parallel consistent.

2024-03-27 21:09 UTC, gsgall commented
@loganharbour @simopier This should be good to go.

2024-03-27 21:40 UTC, loganharbour reviewed
My last comment. Content with everything else

2024-03-27 21:40 UTC, loganharbour commented on include/userobjects/ParticleStepperBase.h
> +#include "RayTracingStudy.h"
```suggestion
#include "GeneralUserObject.h"

#include "VariableSampler.h"

class Ray;
```

2024-03-28 03:51 UTC, simopier requested changes
Thank you for these improvements, @gsgall. I have a few more minor comments and two suggestions:
- could you add a test case for the constant electric field case?
- I encourage you to add a reference to your submitted PBNC paper in the relevant documentation pages. This will improve its visibility. You can lark it as `submitted`, and we'll update this when it gets published.

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/BorisStepper.md
> +The implementation of the Boris algorithm was verified using several single particle motion tests: constant electric field, cyclotron motion ([/cyclotron_motion.i]), and $\vec{E} \times \vec{B}$ drif
Are you adding the constant electric field case to this PR? I think you should since it's in the paper and people might be looking for it, and I think you should link the input in here like we did for the cyclotron motion test, for example.

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +When charged particles are only subjected to an electric field a standard particle stepping scheme called the leapfrog scheme is used to accurately calculate the motion of these particles through the
```suggestion
When charged particles are only subjected to an electric field, a standard particle stepping scheme called the leapfrog scheme can be used to accurately calculate the motion of these particles through the field. This scheme can reproduce particle paths exactly, to machine precision, in the case of a constant uniform electric field. More information about this particle stepping scheme can be found in [!cite](Birdsall_Langdon_1991).
```

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +Where $\vec{v}_{0}$ is the initial particle velocity, $q$, and $m$ are the particles charge and mass, $\vec{F}_0$ is the initial force field the particle is subject to, and $\vec{v}_{1/2}$ is the par
```suggestion
where $\vec{v}_{0}$ is the initial particle velocity, $q$, and $m$ are the particles charge and mass, $\vec{F}_0$ is the initial force field the particle is subject to, and $\vec{v}_{1/2}$ is the particle velocity 1/2 of a time step after the simulation start time.
```

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +Where $\vec{r}_{1}$ is the particles' position after the first time step has been taken and $\vec{r}_0$ is the initial position of the particle. On the $n^\text{th}$ step after the initial step both
```suggestion
where $\vec{r}_{1}$ is the particles' position after the first time step has been taken and $\vec{r}_0$ is the initial position of the particle. On the $n^\text{th}$ step after the initial step both the particles' velocity and postition are updated with a full time step
```

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +Where $\vec{v}_{n + 1/2}$ is the particles' velocity at a time which is 1/2 of a time step after the time at time step $n$, and $\vec{v}_{n - 1/2}$ is the particles' velocity at a time which is 1/2 o
```suggestion
where $\vec{v}_{n + 1/2}$ is the particles' velocity at a time which is 1/2 of a time step after the time at time step $n$, and $\vec{v}_{n - 1/2}$ is the particles' velocity at a time which is 1/2 of a time step before the time at time step $n$. Then the new particle position is updated using the velocity from 1/2 step in the future.
```

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +Where $\vec{r}_{n}$ is the particles position at the time corrisponding to the $n^\text{th}$ time step and $\vec{r}_{n-1}$ is the particles position on the previous time step.
```suggestion
where $\vec{r}_{n}$ is the particles position at the time corresponding to the $n^\text{th}$ time step and $\vec{r}_{n-1}$ is the particles position on the previous time step.
```

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +The implementation of the Leap frog scheme was verified using single particle motion tests: parallel acceleration in an electric field ([/parallel_acceleration.i]), and projectile motion ([/projectil
```suggestion
The implementation of the leap frog scheme was verified using single particle motion tests: parallel acceleration in an electric field ([/parallel_acceleration.i]), and projectile motion ([/projectile_motion.i]).
```

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/LeapFrogStepper.md
> +The implementation of the Leap frog scheme was verified using single particle motion tests: parallel acceleration in an electric field ([/parallel_acceleration.i]), and projectile motion ([/projectil
Thanks for the references to the inputs!

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/ParticleStepperBase.md
> +`ParticleStepperBase` is the abstract class form which all steppers should be derived. `ParticleStepperBase` provides the basic method to update a particles direction and maximum distance based on th
```suggestion
`ParticleStepperBase` is the abstract class form which all steppers should be derived. `ParticleStepperBase` provides the basic method to update a particle's direction and maximum distance based on the velocity stored in ray data, the current time step, and dimension of the mesh. In the provided method `setMaxDistanceAndDirection` the direction is set based on the dimension of the mesh, and the maximum distance is set with the following rule:
```

2024-03-28 03:51 UTC, simopier commented on doc/content/source/userobjects/ParticleStepperBase.md
> +Where $d_\text{max}$ is maximum distance the particle is allowed to travel during the nex time step, and $\vec{v}$ is the particles' velocity.
```suggestion
where $d_\text{max}$ is maximum distance the particle is allowed to travel during the next time step, and $\vec{v}$ is the particles' velocity.
```

2024-03-28 03:51 UTC, simopier commented on include/userobjects/ParticleStepperBase.h
> +  ///@}
I don't get why we needed these methods since they are unused.

2024-03-28 03:51 UTC, simopier commented on test/include/userobjects/TestSimpleStepper.h
> +// MOOSE Includes
```suggestion
```

2024-03-28 03:51 UTC, simopier commented on test/include/userobjects/TestSimpleStepper.h
> +   * A simple particle stepper which will not modify the velocity of the paritcle
```suggestion
   * A simple particle stepper which will not modify the velocity of the particle
```

2024-03-28 03:51 UTC, simopier commented on test/src/userobjects/TestPICStudyUserDefinedRays.C
> +  params.addParam<Real>("charge", 0, "The charge of the particles used for during a test");
```suggestion
  params.addParam<Real>("mass", 0, "The mass of the particles used for a test");
  params.addParam<Real>("charge", 0, "The charge of the particles used for a test");
```

2024-03-28 03:51 UTC, simopier commented on test/tests/userobjects/leapfrog_stepper/tests
> +    requirement = 'The system shall be capable of applying a linear impluse from a force field perpendicular to a particles initial velocity'
```suggestion
    requirement = 'The system shall be capable of applying a linear impulse from a force field perpendicular to a particle's initial velocity'
```

2024-03-28 03:51 UTC, simopier commented on test/tests/userobjects/leapfrog_stepper/tests
> +    requirement = 'The system shall be capable of applying a linear impluse from a force field parallel to a particles velocity'
```suggestion
    requirement = 'The system shall be capable of applying a linear impulse from a force field parallel to a particle's velocity'
```

2024-03-28 05:02 UTC, gsgall commented on include/userobjects/ParticleStepperBase.h
> +  ///@}
These are virtual methods in the abstract base class UserObject from which GeneralUserObject is derived and when creating a non-abstract child class from an abstract base class all of the virtual methods must be given an implementation. So we have to override them even if we are not using them because the ParticleStepperBase is not an abstract class.

2024-03-28 05:08 UTC, gsgall commented on doc/content/source/userobjects/BorisStepper.md
> +The implementation of the Boris algorithm was verified using several single particle motion tests: constant electric field, cyclotron motion ([/cyclotron_motion.i]), and $\vec{E} \times \vec{B}$ drif
Those tests were in the leapfrog stepper section of tests since Boris with no Magnetic field is the same as the leap frog stepper. But I have added these tests to the Boris stepper suite as well for good measure and updated the documentation to link to them as well.

2024-03-28 05:32 UTC, gsgall commented
> Thank you for these improvements, @gsgall. I have a few more minor comments and two suggestions:
> 
> * could you add a test case for the constant electric field case?
> * I encourage you to add a reference to your submitted PBNC paper in the relevant documentation pages. This will improve its visibility. You can lark it as `submitted`, and we'll update this when it gets published.

I have added these test cases for the BorisStepper I also left a comment about them on your review requests where you ask for them as well. 

Additionally, the paper reference has been added to the BorisStepper documentation page.

2024-03-28 13:57 UTC, simopier approved these changes
Thanks @gsgall, this looks great to me. 

@loganharbour, could we add the json file capabilities you mentioned to make the gold file more human readable? Maybe in a follow up PR if it isn't ready to go in yet.

2024-03-28 14:41 UTC, loganharbour commented
> @loganharbour, could we add the json file capabilities you mentioned to make the gold file more human readable? Maybe in a follow up PR if it isn't ready to go in yet.

Yeah, this'll be a future effort. It's on a list :)

2024-03-28 14:41 UTC, loganharbour approved these changes

2024-03-28 15:11 UTC, merged