Bounding Box IC complete
idaholab/salamander pull request #43
Opened 2024-06-13 14:22 UTC by gsgall

- Uniform element sampling has been refactored for flexibility
- The element uniform sampler has also been simplified interally
- Closes #42

2024-06-13 14:31 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2286614/) on 0c6798a wanted to post the following:

View the site [here](https://fenix-dev.hpc.inl.gov/PRs/43/site)

This comment will be updated on new commits.

2024-06-13 15:15 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2286618/) on 0c6798a wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>779711</th>
      <th colspan=4>#43 0c6798</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>93.62%</td>
      <td>94.53%</td>
      <td>+0.92%</td>
      <td>97.57%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>396</td>
      <td>467</td>
      <td>+71</td>
      <td>201</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>27</td>
      <td>27</td>
      <td>-</td>
      <td>5</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://fenix-dev.hpc.inl.gov/PRs/43/coverage_diff)

[Full coverage report](https://fenix-dev.hpc.inl.gov/PRs/43/coverage)



This comment will be updated on new commits.

2024-06-14 14:32 UTC, loganharbour commented
Is this ready for review?

2024-06-14 14:34 UTC, gsgall commented
> Is this ready for review?

Yessir, this is ready!

2024-06-14 14:53 UTC, loganharbour requested changes
Minor changes, I think.

We should do a crash course soon on the action system so that we can start simplifying the input some.

2024-06-14 14:53 UTC, loganharbour commented on doc/content/source/userobjects/BoundingBoxInitializer.md
> +# BoundingBoxInitializer
I think this name might be a little vague; there's nothing that suggests that it's for particles. What do you think?

2024-06-14 14:53 UTC, loganharbour commented on include/userobjects/BoundingBoxInitializer.h
> +  const std::vector<std::vector<Real>> _planes;
Missing a docstring

2024-06-14 14:53 UTC, loganharbour commented on src/userobjects/BoundingBoxInitializer.C
> +  std::vector<std::string> top_right_stirngs = {"x2", "y2", "z2"};
```suggestion
  const std::vector<std::string> bottom_left_strings = {"x1", "y1", "z1"};
  const std::vector<std::string> top_right_strings = {"x2", "y2", "z2"};
```

2024-06-14 14:53 UTC, loganharbour commented on src/userobjects/BoundingBoxInitializer.C
> +BoundingBoxInitializer::getParticleData() const
It looks like there's a lot of fancy logic here that is dimension dependent. Why not force the bounding box to have the proper dimensions of the mesh? I think it's more intuitive that way.

That is, if you have a 2D mesh that is in a plane that isn't at z = 0, you should include that in the bounding box. You then just pass the box params as two points instead.

2024-06-14 14:53 UTC, loganharbour commented on src/userobjects/BoundingBoxInitializer.C
> +                                   _velocity_distributions[2]->quantile(generator.rand()));
Order of evaluation for c function parameters is not guaranteed by the standard. That is, we can't guarantee that we'll first evaluate the first input, then second, then third. Which could lead to inconsistencies in the random generation. You should do this as such:

```
for (const auto i : make_range(uint(3)))
  temp_data.velocity(i) = _velocity_distributions[0]->quantile(generator.rand();
```

to force that we generate x, then y, then z.

2024-06-14 14:53 UTC, loganharbour commented on src/userobjects/BoundingBoxInitializer.C
> +        InitialParticleData temp_data;
Do this instead to do this all in place and avoid copy constructing the data again.

```
auto & particle = data.emplace_back();
```

`emplace_back` will construct a new one, and return a ref to it

2024-06-14 14:53 UTC, loganharbour commented on src/userobjects/BoundingBoxInitializer.C
> +  std::vector<InitialParticleData> data = std::vector<InitialParticleData>();
```suggestion
  std::vector<InitialParticleData> data;
```

The default constructor for std::vector is just an empty vector, so the RHS is redundant

2024-06-14 14:53 UTC, loganharbour commented on src/userobjects/InitializerBase.C
> +  for (const DistributionName & name : _distribution_names)
```suggestion
  // Needed because distributions are constructed after UserObjects
  for (const DistributionName & name : _distribution_names)
```

2024-06-14 14:53 UTC, loganharbour commented on src/userobjects/InitializerBase.C
> +               "You must provide 3 distributions, one for each velocity component.");
You should be able to move this check to earlier in the constructor, checking `_distribution_names`

2024-06-14 14:53 UTC, loganharbour commented on test/tests/userobjects/bounding_box_initiailizer/elements/tests
> +  issues = '#36'
Something cool about tests is that you can extend a requirement, like this

```
[Tests]
  [rays]
    requirement = 'The system shall support placing particles within a bounding box uniformly in a parallel consistent manner in the element type'
    [edge2]
      ...
      detail = 'EDGE2'
    []
    [tri3]
      ...
      detail = 'TRI3'
    []
    ....
  []
[]

2024-06-14 18:11 UTC, simopier requested changes
Thank you for this contribution! 
I added some comments on top of Logan's review.

2024-06-14 18:11 UTC, simopier commented on doc/content/source/userobjects/BoundingBoxInitializer.md
> +# BoundingBoxInitializer
I agree. `ParticleBoundingBoxInitializer` maybe (to be consistent with `ParticlesPerElementInitializer`)?

2024-06-14 18:11 UTC, simopier commented on doc/content/source/userobjects/BoundingBoxInitializer.md
> +This method does not give explict control over the total number of macro particles per element that will be created. If an entire element is contained within the bounding box, however, if a part of a
```suggestion
This method provides the desired macro particle density, but does not give explicit control over the total number of macro particles per element that will be created within the bounding box. If an entire element is contained within the bounding box, then that element will contain the requested number of particles per element. However, if only part of an element is contained within a bounding box, then it will contain a smaller number of particles per element, which is proportional to the fraction of the its volume contained in the bounding box.
```
Please adjust as needed.

2024-06-14 18:11 UTC, simopier commented on doc/content/source/userobjects/BoundingBoxInitializer.md
> +
Please expand on how you do this. Present the main user inputs and steps of the algorithm. 
Otherwise the note you are providing here lacks context.

2024-06-14 18:11 UTC, simopier commented on include/userobjects/BoundingBoxInitializer.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion ENergy Integrated multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//* https://mooseframework.inl.gov/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
//*
//* Copyright 2024, Battelle Energy Alliance, LLC
//* ALL RIGHTS RESERVED
//*
```
The header is being updated. Doing this here will avoid having to update these files later on - see #45

2024-06-14 18:11 UTC, simopier commented on include/utils/ElementSampler.h
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion ENergy Integrated multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//* https://mooseframework.inl.gov/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
//*
//* Copyright 2024, Battelle Energy Alliance, LLC
//* ALL RIGHTS RESERVED
//*
```
The header is being updated. Doing this here will avoid having to update these files later on - see #45

2024-06-14 18:11 UTC, simopier commented on src/userobjects/BoundingBoxInitializer.C
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion ENergy Integrated multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//* https://mooseframework.inl.gov/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
//*
//* Copyright 2024, Battelle Energy Alliance, LLC
//* ALL RIGHTS RESERVED
//*
```
The header is being updated. Doing this here will avoid having to update these files later on - see #45

2024-06-14 18:11 UTC, simopier commented on src/utils/ElementSampler.C
> +//* https://www.gnu.org/licenses/lgpl-2.1.html
```suggestion
//* This file is part of FENIX: Fusion ENergy Integrated multiphys-X,
//* A multiphysics application for modeling plasma facing components
//* https://github.com/idaholab/fenix
//* https://mooseframework.inl.gov/fenix
//*
//* FENIX is powered by the MOOSE Framework
//* https://www.mooseframework.inl.gov
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
//*
//* Copyright 2024, Battelle Energy Alliance, LLC
//* ALL RIGHTS RESERVED
//*
```
The header is being updated. Doing this here will avoid having to update these files later on - see #45

2024-06-14 18:11 UTC, simopier commented on src/userobjects/BoundingBoxInitializer.C
> +    mooseError("Params 'y1' and 'y2' should not be set in 1D simulations");
Why not just return a warning and ignore the y1 and y2 values, rather than return an error? 
This would make going down in dimensions easier for the user.

2024-06-14 18:11 UTC, simopier commented on src/userobjects/BoundingBoxInitializer.C
> +    mooseError("Params 'z1' and 'z2' should not be set unless you are performing a 3D simulation");
Why not just return a warning and ignore the z1 and z2 values, rather than return an error? 
This would make going down in dimensions easier for the user.

2024-06-14 18:11 UTC, simopier commented on src/userobjects/BoundingBoxInitializer.C
> +          }
```suggestion
          plane_value += node(j) * _planes[i][j];
```

2024-06-14 18:11 UTC, simopier commented on src/userobjects/BoundingBoxInitializer.C
> +        }
```suggestion
        intersection_count++;
```

2024-06-14 18:11 UTC, simopier commented on test/tests/userobjects/bounding_box_initiailizer/elements/1d.i
If we change the name of the class, then update the name of this test folder to `particle_bounding_box_initializer`

In any case, you have a typo in `initializer` (one extra `i`).

2024-06-14 18:11 UTC, simopier commented on test/tests/userobjects/bounding_box_initiailizer/elements/1d.i
> +    x2 = 4.25
Why these specific values? 
If there is a reason, maybe add a comment in the input file.

2024-06-14 18:11 UTC, simopier commented on test/tests/userobjects/bounding_box_initiailizer/elements/2d.i
> +    y2 = 5.7
Why these specific values? 
If there is a reason, maybe add a comment in the input file.

2024-06-14 18:11 UTC, simopier commented on test/tests/userobjects/bounding_box_initiailizer/elements/3d.i
> +    z2 = 8.3
Why these specific values? 
If there is a reason, maybe add a comment in the input file.

2024-06-14 18:11 UTC, simopier commented on test/tests/userobjects/bounding_box_initiailizer/elements/tests
> +  design = 'InitializerBase.md ParticlesPerElementInitializer.md ElementSampler.md'
```suggestion
  design = 'InitializerBase.md ParticlesPerElementInitializer.md ElementSampler.md ParticleBoundingBoxInitializer.md'
```

2024-06-14 18:11 UTC, simopier commented on test/tests/userobjects/bounding_box_initiailizer/elements/3d.i
> +    z2 = 8.3
I'm guessing/hoping you try cases where you cut your elements in the complex ways that you try to capture in the code. A comment would make this more explicit.

2024-06-14 18:11 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/gold/prism6_out.csv
Where is this difference coming from?

2024-06-14 18:11 UTC, simopier commented on test/tests/userobjects/particles_per_element_initializer/elements/gold/tri3_out.csv
Where is this difference coming from?

2024-06-17 14:16 UTC, gsgall commented
> Minor changes, I think.
> 
> We should do a crash course soon on the action system so that we can start simplifying the input some.

Yeah I think that would be a great help!

2024-06-17 14:17 UTC, gsgall commented on doc/content/source/userobjects/BoundingBoxInitializer.md
> +# BoundingBoxInitializer
I agree with this being an issue, I think something like `OtherDescriptionParticleInitializer` would be a good way to set a standard. I will make this change

2024-06-17 15:41 UTC, gsgall commented on src/userobjects/BoundingBoxInitializer.C
> +    mooseError("Params 'y1' and 'y2' should not be set in 1D simulations");
I think that making this a waning is fine. The method already does the ignoring of higher dimensional parameters when checking if a point is within an element. I think this is also pretty similar to a comment @loganharbour had about the dimensional logic. What are your thoughts on this Logan?

2024-06-17 15:41 UTC, gsgall commented on src/userobjects/BoundingBoxInitializer.C
> +    mooseError("Params 'z1' and 'z2' should not be set unless you are performing a 3D simulation");
Repeat comment

2024-06-17 15:44 UTC, gsgall commented on test/tests/userobjects/bounding_box_initiailizer/elements/3d.i
> +    z2 = 8.3
That is a correct assumption. I chose these values so that the elements would get chopped up in non-predictable ways. I'll add a comment in the input file and mark all of the duplicate comments about this as resolved.

2024-06-17 15:45 UTC, gsgall commented on test/tests/userobjects/bounding_box_initiailizer/elements/2d.i
> +    y2 = 5.7
See comments on 

```
test/tests/userobjects/bounding_box_initiailizer/elements/3d.i
```

2024-06-17 15:45 UTC, gsgall commented on test/tests/userobjects/bounding_box_initiailizer/elements/1d.i
> +    x2 = 4.25
See comments on 

```
test/tests/userobjects/bounding_box_initiailizer/elements/3d.i
```

2024-06-17 15:49 UTC, gsgall commented on test/tests/userobjects/particles_per_element_initializer/elements/gold/prism6_out.csv
The difference here and the same is true for the tri3 is that I simplified the method used for mirroring the particles. The original implementation would calculate the distance from the particle location to the line which cut the rectangular prism into two triangular prisms and then mirror over this line. This involves some more square roots and is a little more ambiguous in my opinion. The implementation was shifted to use two subtraction operations to fold points into the desired element, for simplicity. 

To unsure this maintains the desired effects of uniformly sampling the space within the elements the original convergence studies were performed again and if you would like we can get together and go over those results again. But results for those studies are as expected.

2024-06-17 15:49 UTC, gsgall commented on test/tests/userobjects/particles_per_element_initializer/elements/gold/tri3_out.csv
See comment on 

`test/tests/userobjects/particles_per_element_initializer/elements/gold/prism6_out.csv`

2024-06-17 18:32 UTC, loganharbour commented on doc/content/source/userobjects/BoundingBoxInitializer.md
> +# BoundingBoxInitializer
thanks! We try to avoid general object names because once you combine applications together, it's easy to get collisions with object names which will just not work

2024-06-17 21:19 UTC, gsgall commented on include/userobjects/BoundingBoxInitializer.h
> +  const std::vector<std::vector<Real>> _planes;
Added the string

2024-06-17 21:26 UTC, gsgall commented on src/userobjects/BoundingBoxInitializer.C
> +BoundingBoxInitializer::getParticleData() const
I can adjust the input to use 2 points I agree that it would be a bit more intuitive. The only thing to note is the if say we are in 2D where the mesh isn't at z=0 then I don't even consider the z value of the bounding box provided by the user. The points sampled will always be within the actual plane in 2D and on the actual mesh line in 1D since we sample reference elements and then map them to real elements.

2024-06-17 21:27 UTC, gsgall commented on src/userobjects/BoundingBoxInitializer.C
> +                                   _velocity_distributions[2]->quantile(generator.rand()));
Yeah that makes sense, thank you for the explanation. I ran into a similar issue actually with my original implementation of the `ParticlesPerElementInitializer` This change has been adopted

2024-06-17 21:32 UTC, gsgall commented on src/userobjects/InitializerBase.C
> +               "You must provide 3 distributions, one for each velocity component.");
That's a good point I have moved this check into the body of the constructor.

2024-06-17 22:28 UTC, gsgall commented on src/userobjects/BoundingBoxInitializer.C
> +        InitialParticleData temp_data;
This is great! Thank you for showing me this.

2024-06-17 22:43 UTC, gsgall commented on src/userobjects/BoundingBoxInitializer.C
> +BoundingBoxInitializer::getParticleData() const
To help give users a warning about this I am just giving a warning for any simulation using the bounding box that is not a 3D simulation.

2024-06-17 22:43 UTC, gsgall commented on test/tests/userobjects/bounding_box_initiailizer/elements/tests
> +  issues = '#36'
I have made this change.

2024-06-17 22:44 UTC, gsgall commented on src/userobjects/BoundingBoxInitializer.C
> +    mooseError("Params 'y1' and 'y2' should not be set in 1D simulations");
I have updated this to give a warning for any simulation that is not a 3D simulation. The warning just tells the user that any additional components above the simulation dimension are going to be ignored.

2024-06-17 23:26 UTC, gsgall commented on test/tests/userobjects/bounding_box_initiailizer/elements/1d.i
I have reorganized a bit so this shouldn't be an issue

2024-06-18 17:22 UTC, gsgall commented on test/tests/userobjects/bounding_box_initiailizer/elements/tests
> +  design = 'InitializerBase.md ParticlesPerElementInitializer.md ElementSampler.md'
These were addressed using a different convention

2024-06-18 17:40 UTC, gsgall commented on doc/content/source/userobjects/BoundingBoxInitializer.md
> +
I added a bit more context to this as well

2024-06-18 18:04 UTC, gsgall commented on doc/content/source/userobjects/BoundingBoxInitializer.md
> +This method does not give explict control over the total number of macro particles per element that will be created. If an entire element is contained within the bounding box, however, if a part of a
I have added a bit more detail and adjusted the note.

2024-06-18 21:32 UTC, gsgall commented
@loganharbour @simopier Is there a reason my Civet testing for this PR has disappeared?

2024-06-19 14:42 UTC, gsgall commented
> @loganharbour @simopier Is there a reason my Civet testing for this PR has disappeared?

I see the issue was a merge conflict in the MOOSE submodule, not really sure how that happened.

2024-06-19 15:04 UTC, gsgall commented
@loganharbour @simopier I believe I have address all of the requested changes, this should be ready for your review.

2024-06-23 23:25 UTC, loganharbour approved these changes

2024-06-23 23:25 UTC, loganharbour requested changes
Needs a rebase

2024-06-24 05:22 UTC, simopier requested changes
Great stuff, thank you! I'd like to see a couple of minor changes. 

One thing I am also wondering about: 
Do we need all these exodus files with `e-s000x`? Couldn't we just one the last one? Are they even all used in tests? 
I know you did not add them in this PR, you are just moving them. So this might need to be addressed in a different PR, but I wanted to ask.

2024-06-24 05:22 UTC, simopier commented on doc/content/source/userobjects/BoundingBoxParticleInitializer.md
> +In this intiailizer first all of the elements that are at least partially contained within the requested bounding box are collected. Then the requested number (`particles_per_element`) of spatial loc
```suggestion
In this initializer, all of the elements that are at least partially contained within the requested bounding box are first collected. Then, the requested number (`particles_per_element`) of spatial locations are sampled within each element. Finally, all potential particle locations which are within the element but are not within the bounding box are discarded.
```

2024-06-24 05:22 UTC, simopier commented on doc/content/source/userobjects/BoundingBoxParticleInitializer.md
> +This method does not give explict control over the number of macro particles per element that will be created. If an entire element is contained within the bounding box, then that element will contai
```suggestion
This method does not give explict control over the number of macro particles per element that will be created. If an entire element is contained within the bounding box, then that element will contain the requested particles per element. On average elements which are partially contained within the bounding box will contain a number of macro particles approximately proportional to the fraction of the elements' volume that is contained within the bounding box.
```

2024-06-24 14:00 UTC, gsgall commented
> Great stuff, thank you! I'd like to see a couple of minor changes.
> 
> One thing I am also wondering about: Do we need all these exodus files with `e-s000x`? Couldn't we just one the last one? Are they even all used in tests? I know you did not add them in this PR, you are just moving them. So this might need to be addressed in a different PR, but I wanted to ask.

@loganharbour feel free to correct me on this but I believe that the `e-s000x` files contain the data about the rays on each step taken.

- All of those are used in the tests I have written
- In terms of using just the last one. I will defer to @loganharbour on this about what is the standard practice for these sorts of ray tests. My intuition says that it would be better to test the state on each time step for a couple of reasons. If we are going to make this change I agree that it would be better to address this request in a different PR.
  
  -  The time steppers have behavior which depends on the number of steps taken (taking the 1/2 step in velocity initially) and using all of the `e-000x` files helps ensure that this behavior is retained.
  - In the worst case scenario of making a change if we only have the final step then you could potentially just replace the implementation so that state of the ray at the final step matches just to make the test pass (but I don't know if this is a real concern or not)

2024-06-24 15:35 UTC, loganharbour commented
I don't have any problem with storing multiple steps and I think it makes sense. However, we should probably avoid testing with that many steps in the future. It's not really necessary, as 2 or 3 is sufficient for unit testing

2024-06-25 04:06 UTC, closed without merging

2024-06-25 04:39 UTC, simopier commented
@loganharbour this should not have been closed, could you please re-open it?

2024-06-25 04:44 UTC, simopier commented
> I believe that the e-s000x files contain the data about the rays on each step taken.

Yes, this is correct. 

> I don't have any problem with storing multiple steps and I think it makes sense. However, we should probably avoid testing with that many steps in the future. It's not really necessary, as 2 or 3 is sufficient for unit testing

I don't think this is a big deal for these tests, but like Logan said, we could probably get the same quality of test with fewer time steps. The right number of steps to test would of course depend on the nature of the test/physics.

2024-06-25 13:01 UTC, loganharbour commented
> @loganharbour this should not have been closed, could you please re-open it?

Looks like all forked repo links were removed when we made the repo public. Not sure why this happened. Nothing on github suggests it would happen.

I resolved this by deleting my forked repo, re-forking it, and then pushing all of my branches back to my "new" fork with

```
git push origin --all
```

We'll need to do that with Grayson's fork and re-create the PR. I sent in a support ticket to GH to ask what happened.

2024-06-25 13:17 UTC, gsgall commented
> > @loganharbour this should not have been closed, could you please re-open it?
> 
> Looks like all forked repo links were removed when we made the repo public. Not sure why this happened. Nothing on github suggests it would happen.
> 
> I resolved this by deleting my forked repo, re-forking it, and then pushing all of my branches back to my "new" fork with
> 
> ```
> git push origin --all
> ```
> 
> We'll need to do that with Grayson's fork and re-create the PR. I sent in a support ticket to GH to ask what happened.

I have done this and the new PR is #50