CAD workflow documentation
idaholab/salamander pull request #73
Opened 2024-10-07 04:54 UTC by meltawila

This PR is to add CAD-based Geometry Workflow example for Multiphysics Fusion Problems Using OpenMC and MOOSE. Work and results taken from M. Eltawila, A. J. Novak, P.C. A. Simon, G. Giudicelli, D. Gaston, “Investigating CAD-based Geometry Workflows for Multiphysics Fusion Problems Using OpenMC and MOOSE,” Submitted to Pacific Basin Nuclear Conference (PBNC) (2024).

(Ref. #30)

2024-10-07 05:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2485383/), step Size check on 679d5d1 wanted to post the following:

Warning: This PR changes repo size by 13.20 MiB.

2024-10-07 05:35 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2485387/), step Sync to remote on 679d5d1 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/fenix/docs/PRs/73/site)

This comment will be updated on new commits.

2024-10-07 05:55 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2485420/), step Size check on 3367918 wanted to post the following:

Warning: This PR changes repo size by 13.79 MiB.

2024-10-07 06:05 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2485442/), step Size check on 49b1e2c wanted to post the following:

Warning: This PR changes repo size by 13.79 MiB.

2024-11-04 17:48 UTC, cticenhour requested changes
Quick comment I wanted to note, before this gets to formal review. CIVET is throwing a warning that this PR is too large (storage-wise), and I agree. We should work toward a minimum usable size for image files (`doc/content/figures/cad_workflow_d1.png` and `doc/content/figures/cad_workflow_mesh_1.png` are notable examples), and a minimum testable size for gold files.

2024-11-04 18:18 UTC, meltawila commented
@cticenhour Should I omit `Exodiff` tests and only use `Csvdiff` instead to reduce /gold size?

2024-11-08 15:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2537835/), step Size check on 987ab3e wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2024-11-08 16:38 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2537924/), step Size check on 7f93c3a wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2024-11-22 03:11 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2559266/), step Size check on da0d9f9 wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2024-11-22 03:48 UTC, meltawila commented
@loganharbour I think CIVET should call `cardinal/scripts/download-openmc-cross-sections.sh` here and set `OPENMC_CROSS_SECTIONS` similar to what happens for Cardinal. Could you help with this please?

2024-12-02 20:31 UTC, loganharbour requested changes
Please remove the moose submodule update. XS should be good to go now

2024-12-06 15:12 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2587266/), step Size check on 44f8da3 wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-29 03:48 UTC, simopier requested changes
Here are some comments and suggestions to get this going. Things look good!

I still need to run this locally and check the online documentation (the one from the PR is out of date, but will be re-generated after you push these changes).

A bit more background about some of the suggestions:
- `temperature` is better than `temp` for variable name. `temp` could mean `temporary`, or something else. `temperature` increases consistency and reduces confusion. 
- The `${units }` system is a very convenient way to determine the unit of the parameters. It can even do unit conversions when needed. Make sure to use it whenever possible.

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/index.md
>  FENIX is under active development and does not currently have any example cases available to users.
```suggestion
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/openmc.i
> +  [vol]
```suggestion
  [volume]
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/openmc.i
> +    temperature = temp
```suggestion
    temperature = temperature
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/openmc.i
> +    tally_score = h3_production
```suggestion
    tally_score = tritium_production
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/openmc.i
> +    variable = H3_production
```suggestion
    variable = tritium_production
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/openmc.i
> +      score = 'heating_local H3_production'
```suggestion
      score = 'heating_local tritium_production'
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +  [temp]
```suggestion
  [temperature]
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    initial_condition = 800.0 # [K]
```suggestion
    initial_condition = ${initial_temperature}
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +[Mesh]
```suggestion
# Conditions
initial_temperature = ${units 800.0 K} 

# Material properties
thermal_conductivity_armor = ${units 1.64 W/m/K}
thermal_conductivity_FW = ${units 0.45 W/m/K}
thermal_conductivity_BM = ${units 0.65 W/m/K}

[Mesh]
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    variable = temp
```suggestion
    variable = temperature
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    variable = temp
```suggestion
    variable = temperature
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    variable = temp
```suggestion
    variable = temperature
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    value = 800.0 # [K]
```suggestion
    value = ${initial_temperature}
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +  [temp_to_openmc]
```suggestion
  [temperature_to_openmc]
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    variable = temp
```suggestion
    variable = temperature
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    source_variable = temp
```suggestion
    source_variable = temperature
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    variable = temp
```suggestion
    variable = temperature
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +  [max_T]
```suggestion
  [max_temperature]
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    prop_values = '1.64' # [W/m.K]
```suggestion
    prop_values = ${thermal_conductivity_armor}
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    prop_values = '0.45'  # [W/m.K]
```suggestion
    prop_values = ${thermal_conductivity_FW}
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    prop_values = '0.65'  # [W/m.K]
```suggestion
    prop_values = ${thermal_conductivity_BM}
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +The results of the coupled neutronics and heat transfer model are shown in [tok_temps] and [tok_h3production] for the temperature distribution and tritium production rate density.
```suggestion
The results of the coupled neutronics and heat transfer model are shown in [tokamak_temperatures] and [tokamak_tritium_production] for the temperature distribution and tritium production rate density.
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +  id=tok_temps
```suggestion
  id=tokamak_temperatures
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +  id=tok_h3production
```suggestion
  id=tokamak_tritium_production
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +In this example, you'll learn how to:
```suggestion
This example demonstrates how to:
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +- Couple OpenMC [!cite](openmc) and MOOSE [!cite](giudicelli2024moose) using Cardinal for fixed source Monte Carlo calculations.
```suggestion
- Couple OpenMC [!cite](openmc) and MOOSE [!cite](giudicelli2024moose) using Cardinal within FENIX for fixed source Monte Carlo calculations.
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +- Use Cardinal [!cite](novak2022_cardinal) to tally values of interest such as tritium production and heating which would be used in MOOSE to solve for the temperature distribution
```suggestion
- Use Cardinal [!cite](novak2022_cardinal) to tally values of interest such as tritium production and heating which would be used in FENIX to solve for the temperature and tritium distributions.
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +We describe this workflow for a generic CAD model which is extremely simplified for the purpose of presenting the modeling workflow. This model was also used in [!cite](Eltawila2024PBNC) to perform m
```suggestion
We describe this workflow for a generic CAD model which is extremely simplified for the purpose of the demonstration. Nonetheless, the same workflow is applicable to more complex CAD geometries. This model was also used in [!cite](Eltawila2024PBNC) to perform mesh refinement studies to investigate how the mesh refinement level affects multiphysics results. The meshed geometry was prepared using direct accelerated geometry Monte Carlo (DAGMC) for particle transport, and a volumetric mesh was also prepared to be used in MOOSE’s finite element solver and to tally OpenMC results for heat source distribution and tritium production. Cardinal was used to run OpenMC Monte Carlo particle transport within FENIX. The data transfer system transferred heat source and temperature distribution between OpenMC and MOOSE as shown in [transfers], with coupling between neutron transport and heat conduction achieved via Picard iteration.
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +In this example, `tmesh_1.e` ([volumetric_mesh]) is the finite element mesh used in MOOSE on which the heat conduction physics is solved. `tmesh_1.h5m` ([dagmc]) is the DAGMC surface mesh used for pa
```suggestion
In this example, `tmesh_1.e` ([volumetric_mesh]) is the finite element mesh used in MOOSE on which the heat transfer physics is solved. `tmesh_1.h5m` ([dagmc]) is the DAGMC surface mesh used for particle transport in OpenMC (which bounds the surfaces between different materials). Cardinal also allows for mesh tallying for tallying OpenMC results directly on the mesh overlayed on the OpenMC geometry which `tmesh_1.e` ([volumetric_mesh]) could be used for as well as an unstructured volume mesh. This could be used by changing the tally type and adding a mesh template (`tally_type = mesh`, `mesh_template = tmesh_1.e`) in Cardinal input under Problem.
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +The Cardinal input files is shown below. The ([MoabSkinner](https://cardinal.cels.anl.gov/source/userobjects/MoabSkinner.html)) was chosen in this model to update the DAGMC geometry from the MOOSE me
```suggestion
The Cardinal input files is shown below. The ([MoabSkinner](https://cardinal.cels.anl.gov/source/userobjects/MoabSkinner.html)) was chosen in this model to update the DAGMC geometry from the MOOSE mesh directly ensuring meshes matching which is further discussed in [!cite](Eltawila2024PBNC) as well as the use of cell tallies.
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +This will run both MOOSE and OpenMC (with Cardinal) with 2 MPI processes and 2 OpenMP threads per rank. To run the simulation faster, you can increase the parallel processes/threads, or simply decrea
```suggestion
This will run both MOOSE and OpenMC (with Cardinal) with 2 MPI processes and 2 OpenMP threads per rank. To run the simulation faster, you can increase the parallel processes/threads, or simply decrease the number of particles used in OpenMC (note that this might also decrease accuracy). When the simulation has completed, you will have created a number of different output files:
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +The results of this simulation are shown in [temps], [h3production], and [results]. More information - including a mesh sensitivity study and results from a finer mesh - is available in [!cite](Eltaw
```suggestion
The results of this simulation are shown in [temperatures], [tritium_production], and [results]. More information and analysis, including a mesh sensitivity study and results from a finer mesh, is available in [!cite](Eltawila2024PBNC).
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +  id=temps
```suggestion
  id=temperatures
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +  id=h3production
```suggestion
  id=tritium_production
```

2025-01-29 03:48 UTC, simopier commented on doc/content/verification_validation_examples/CAD_based_workflow/CAD_workflow.md
> +| Tritium Production (atoms/s) | 4.70 × 10^13^ ± 8 × 10^11^ |
```suggestion
| Heat Source (W)              | $2.44 \times 10^5^ \pm 3 \times 10^3^$   |
| Tritium Production (atoms/s) | $4.70 \times 10^13^ \pm 8 \times 10^11^$ |
```
It seems like you also have extra `^`

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/solid.i
> +    block = 'Armour'
```suggestion
    block = 'Armor'
```

2025-01-29 03:48 UTC, simopier commented on test/tests/examples/cad_workflow/openmc.i
> +  volume_calculation = vol
```suggestion
  volume_calculation = volume
```

2025-01-30 00:26 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2658696/), step Size check on fe7c80d wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-30 00:29 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2658768/), step Size check on 55c479b wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-30 02:29 UTC, simopier commented
FYI @meltawila, you can go to `files changes` and then do `add suggestion to batch to apply all the suggestions in one commit. 
This helps minimize the number of commits.

2025-01-30 03:23 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2659074/), step Size check on 9a31733 wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-30 04:26 UTC, simopier commented
@meltawila, I see that you added a commit to fix errors, but several of those will be fixed by adding the suggestions that are still pending.

2025-01-30 04:41 UTC, meltawila commented
The tests are passing locally and on Sawtooth, but still fail with timeout error here and with non-unicode characters in output error for the Test debug, which I am not sure how to fix yet. I think the Documentation test would pass with the pending changes yes - I will add these

2025-01-30 04:56 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2659426/), step Size check on a390184 wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-30 04:59 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2659459/), step Size check on b77f1fa wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-30 16:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2660285/), step Size check on 0931f22 wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-30 17:46 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2660522/), step Size check on 7a405ec wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-31 15:06 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2662999/), step Size check on 401388f wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-01-31 19:28 UTC, simopier requested changes
to not run the recover tests

2025-01-31 19:28 UTC, simopier commented on test/tests/examples/cad_workflow/tests
> +    mesh_mode = 'replicated'
```suggestion
    mesh_mode = 'replicated'
    recover = false # see #81
```

2025-01-31 19:28 UTC, simopier commented on test/tests/examples/cad_workflow/tests
> +    mesh_mode = 'replicated'
```suggestion
    mesh_mode = 'replicated'
    recover = false # see #81
```

2025-02-14 22:32 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2692996/), step Size check on d9520d2 wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-02-14 23:23 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2693004/), step Generate coverage on d9520d2 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/fenix/docs/PRs/73/coverage)



This comment will be updated on new commits.

2025-02-14 23:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2693404/), step Size check on 27d2a5d wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-02-14 23:48 UTC, simopier commented
It seems like you are still dealing with an open MC run that takes too long and gets cut. 
One thing you could do is have the current test (maybe even with the previous number of particles and batches) marked with `heavy=true`, and then do a very small test for regular testing - with the strict minimum of particles and batches. 

EDIT: I see you just pushed one more change, we'll se how this one performs

2025-02-15 00:53 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2693702/), step Size check on 8726192 wanted to post the following:

Warning: This PR changes repo size by 5.09 MiB.

2025-02-15 15:11 UTC, simopier requested changes
Let's have both regular and heavy tests, with different number of particles and batches.

2025-02-15 15:11 UTC, simopier commented on test/tests/examples/cad_workflow/tests
> +[Tests]
I'm glad to see these tests pass as heavy. Could you create two others tests (basically the same as you have here, but with an even smaller number of particle and batches using `cli_args = `)? 
This way we still test this in the base tests (see example here: https://mooseframework.inl.gov/TMAP8/verification_and_validation/val-2b.html)

2025-02-15 15:27 UTC, meltawila commented on test/tests/examples/cad_workflow/tests
> +[Tests]
Debug mode was still failing with as low as 50 particles which is extremely low. There is a lower limit as openmc will eventually throw an error if there are no enough source particles in a process. I was trying to see if I can use `debug = false`. The error I am getting is (non-unicode characters in output) even though the test is crashing before hitting the time limit

2025-02-15 15:42 UTC, meltawila commented on test/tests/examples/cad_workflow/tests
> +[Tests]
I will disable photon transport in the regular testing which should be much faster and try again

2025-02-15 19:19 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2694079/), step Size check on 77eb99c wanted to post the following:

Warning: This PR changes repo size by 5.03 MiB.

2025-02-15 19:52 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2694088/), step Size check on 31d39a5 wanted to post the following:

Warning: This PR changes repo size by 6.25 MiB.

2025-02-15 20:20 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2694097/), step Size check on 8702b34 wanted to post the following:

Warning: This PR changes repo size by 6.27 MiB.

2025-02-15 21:03 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2694106/), step Size check on 84250bf wanted to post the following:

Warning: This PR changes repo size by 6.27 MiB.

2025-02-15 21:38 UTC, meltawila commented
I'm unsure if the debug mode test error is still due to exceeding the wall time limit, as it occurs well before the 300-second threshold

2025-02-16 17:15 UTC, simopier commented on test/tests/examples/cad_workflow/n_transport/tests
> -    heavy = true
Why create completely new input files rather than use the `cli_args` option?

2025-02-16 17:28 UTC, meltawila commented on test/tests/examples/cad_workflow/n_transport/tests
> -    heavy = true
I was updating openmc settings.xml input here. It’s neither a FENIX/Cardinal input so I am not sure if it’s possible to use cli_args

2025-02-16 17:29 UTC, meltawila commented on test/tests/examples/cad_workflow/n_transport/tests
> -    heavy = true
I was able to replicate the non unicode in output error locally after I built Fenix with debug method

2025-02-17 22:13 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2695595/), step Size check on 05055f3 wanted to post the following:

Warning: This PR changes repo size by 6.27 MiB.

2025-05-09 19:47 UTC, closed without merging